name: Feature Request
description: Suggest a feature for Petrichor
title: "Feature Request: "
labels: ["feature proposal"]
body:
  - type: markdown
    attributes:
      value: |
        **Note:** Your issue title should start with "Feature Request:" followed by a brief description
        
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What would you like to see added?
      placeholder: "Add ability to sort playlists by date added..."
    validations:
      required: true
      
  - type: textarea
    id: why
    attributes:
      label: Why is this needed?
      placeholder: "Currently there's no way to see which playlists were created recently..."
    validations:
      required: true
      
  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      options:
        - Library Management
        - Playback
        - Playlists
        - Search & Filtering
        - UI/UX
        - File Format Support
        - Performance
        - Other
    validations:
      required: true
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any mockups, examples from other apps, or other details?
      
  - type: checkboxes
    id: checklist
    attributes:
      label: Before submitting
      options:
        - label: I searched existing issues to avoid duplicates
          required: true